displayName=Worn Equip Viewer
author=iGundamStyle,JZomDev
description=Overlay to display Worn Equipment
tags=equipment, items, overlay, viewer, gear
plugins=com.tabsviewer.TabsViewerPlugin
version=1.0.1